import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
const index = props => {
  return (
    <div class="ga-content-panel ga-half-panel ga-total-Commissions">
      <span class="ga-panel-icon">
        <i>
          <FontAwesomeIcon icon="dollar-sign" className="" />
        </i>
      </span>
      <h2># of Commissions</h2>
      <p>Generated by 19 Affiliates</p>
      <span class="ga-panel-data">x591</span>
    </div>
  );
};

export default index;
