import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
const index = props => {
  return (
    <div className="ga-content-panel ga-half-panel ga-total-traffic">
      <span className="ga-panel-icon">
        {" "}
        <i>
          <FontAwesomeIcon icon="chart-line" className="" />
        </i>
      </span>
      <h2>Total Traffic</h2>
      <p>Generated by 19 Affiliates</p>
      <div className="ga-traffic-data">
        <span className="ga-panel-data">849,017</span>
        <div className="ga-traffic-ind">
          {" "}
          <i>
            <FontAwesomeIcon icon="long-arrow-alt-up" className="" />
          </i>
          <span className="ga-traffic-change">23.5%</span>
        </div>
      </div>
    </div>
  );
};

export default index;
