import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

const index = props => {
  return (
    <div className="ga-content-panel ga-half-panel ga-total-Commissions">
      <span className="ga-panel-icon">
        <i>
          <FontAwesomeIcon icon="money-check-alt" className="" />
        </i>
      </span>
      <h2>Total Commissions</h2>
      <p>Generated by 19 Affiliates</p>
      <span className="ga-panel-data">$561,303</span>
    </div>
  );
};

export default index;
